name: sync main with current main-x
on:
  push: 
    branches: [ main ]

permissions:
  pull-requests: write
  contents: write

jobs:
  sync-current-main-with-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.PULL_REQUESTS_ENABLE_CHECKS_TOKEN }}
          FROM_BRANCH: "main"
          TO_BRANCH: "main-0.4"

      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.pull.outputs.PULL_REQUEST_NUMBER }}
          merge-method: merge
